### ISSUE TITLE
InSpy could not identify the domain name. Use --domain.

### ISSUE THREAD

**Issue by DocKali** [leapsecurity/InSpy#14]
Hi,
Thanks @gojhonny for this new version. I actually try to test InSpy 3.0 but I have some problem.

If I understand your tool new version, he needs to have Company Name, email and domain fullfilled to run, right?

Other question, what format is expected for --domain? Whatever I try, y always have in return "InSpy could not identify the domain name. Use --domain."

Thanks for your work and for this new version!

**Comment by gojhonny** [comment]
Hi @DocKali, InSpy v3 solely needs the company name to function. If InSpy can't identify the domain and/or email then it'll prompt you to enter it. You can find some example uses at https://www.leapsecurity.io/blog/linkedin-enumeration-inspy/

To help with troubleshooting can you tell me what arguments you are providing to InSpy? Thanks!

**Comment by gojhonny** [comment]
No problem, InSpy should be able to run for big or small companies as long as they have a LinkedIn profile. Use --domain and --email when you need to.

If it's still giving you issues, it would be good to get an output of the tool showing what error messages you're getting and the arguments you're putting in

**Comment by DocKali** [comment]
You solve my issue, thanks! I forgot that the target must have a LinkedIn profile. I just test it and your tool made a great job! Thanks for your help @gojhonny

**Comment by gojhonny** [comment]
Glad I could help @DocKali. Enjoy! :)

**Comment by hwac121** [comment]
doesn't like email format...not enough instructions and no man page. Not even a website anymore. Should I even use this tool with my pentesting team at all?

**Comment by Alaponuke** [comment]
yes same problem, this tool is deprecated and should be removed and not even use anymore...
