### ISSUE TITLE
0 employees problem

### ISSUE THREAD

**Issue by xinkyo** [leapsecurity/InSpy#16]
![image](https://user-images.githubusercontent.com/43132285/45285279-63511900-b515-11e8-8bee-133646177eed.png)

only 0 employees for whatever company I typed..

**Comment by gojhonny** [comment]
Please ensure you have entered your Hunter API key.

**Comment by xinkyo** [comment]
yes, I already put the API from hunter.io.  it shows 0 employee identified always. never success.

**Comment by gojhonny** [comment]
I can't seem to replicate this issue, works on my end.

**Comment by gojhonny** [comment]
No response.
