### ISSUE TITLE
emails is not defined

### ISSUE THREAD

**Issue by Maleus** [leapsecurity/InSpy#17]
File "./InSpy.py", line 89, in <module>
    output("csv", args.csv, args.company, domain, employees, emails)
NameError: name 'emails' is not defined

Traceback (most recent call last):
  File "./InSpy.py", line 89, in <module>
    output("csv", args.csv, args.company, domain, employees, email)
  File "/root/tools/InSpy/lib/export.py", line 8, in output
    ocsv(file, company, domain, employees, emails)
  File "/root/tools/InSpy/lib/export.py", line 21, in ocsv
    writer.writerow({"Employee Name": name, "Title": title.replace('&amp;', '&'), "Email": emails[name]})
TypeError: string indices must be integers, not str

**Comment by aslarchergore** [comment]
I'm getting the same thing:

**Comment by gojhonny** [comment]
What arguments are you guys using when this happens?

**Comment by aslarchergore** [comment]
Arguments that I used were:

# ./InSpy.py --domain domain.com --titles wordlists/title-list-large.txt
--email first.last@domain.com --csv emails.txt "company"

**Comment by ismisepaul** [comment]
@gojhonny I'm unsure why this was closed when the fix https://github.com/leapsecurity/InSpy/pull/24 was not merged in?

Was there something else that addressed this problem and if not should this not be reopened until the merge is complete?
