### ISSUE TITLE
Invalid Syntax Error

### ISSUE THREAD

**Issue by scrblrus** [leapsecurity/InSpy#19]
I'm not having much luck running the script so far. I got this error when executing. Seems like it would be a quick fix. 

Additionally, I seem to have errors with running empspy. Is that no longer a feature?
  
File "./code.py", line 31
    print "\nInSpy {}".format(parser.version)
                     ^
SyntaxError: invalid syntax

**Comment by gojhonny** [comment]
Hi there,  `techspy` is no longer implemented and `empspy` is no longer a valid argument in InSpy v3. For information and examples on usage refer to the help section of the tool or https://www.leapsecurity.io/blog/linkedin-enumeration-inspy/
