### ISSUE TITLE
Inspy application --empspy and --techspy cannot be found 

### ISSUE THREAD

**Issue by secureitnetworks** [leapsecurity/InSpy#21]
Hi I have installed application Inspy and I cannot found --empspy and --techspy under the options

root@kali:~# inspy -h
usage: inspy [-h] [-v] [--domain DOMAIN] [--email EMAIL] [--titles [file]]
             [--html file] [--csv file] [--json file] [--xml file]
             company

InSpy - A LinkedIn enumeration tool by Jonathan Broche (@LeapSecurity)

positional arguments:
  company          Company name to use for tasks.

optional arguments:
  -h, --help       show this help message and exit
  -v, --version    show program's version number and exit
  --domain DOMAIN  Company domain to use for searching.
  --email EMAIL    Email format to create email addresses with. [Accepted
                   Formats: first.last@xyz.com, last.first@xyz.com,
                   firstl@xyz.com, lfirst@xyz.com, flast@xyz.com,
                   lastf@xyz.com, first@xyz.com, last@xyz.com]
  --titles [file]  Discover employees by title and/or department. Titles and
                   departments are imported from a new line delimited file.
                   [Default: title-list-small.txt]

Output Options:
  --html file      Print results in HTML file.
  --csv file       Print results in CSV format.
  --json file      Print results in JSON.
  --xml file       Print results in XML.
root@kali:~#

**Comment by gojhonny** [comment]
Empspy and Techspy are no longer valid arguments. Please refer to the hep section or https://www.leapsecurity.io/blog/linkedin-enumeration-inspy/ blog post on how to use the new version.
