### ISSUE TITLE
May no longer be working?

### ISSUE THREAD

**Issue by momoisacat** [leapsecurity/InSpy#5]
I recently got this tool, wanted to check out its capabilities. I noticed that when i attempt to use the tool no results show. Has Linkedin updated their web sites to prevent searching?

**Comment by Basil365** [comment]
+1 momoisacat's comment. Loaded OK and script ran, but even when repeating the Microsoft example I received a '0 Employees identified' response.
Either things have been going badly recently in Redland, or there's an issue with the Script or LinkedIn are blocking it

**Comment by absane** [comment]
Same here. My hunch is that LinkedIn changed the format of the responses.

**Comment by gojhonny** [comment]
Hey guys, thanks for the heads up on this! Seems like LinkedIn is changing up their schemes again. Not going to lie here, I am going to be pretty busy for the next couple of weeks and would really appreciate any help fixing this. If you guys can give it a shot, and send it back my way, I'll test it and merge it. Thanks in advance!

**Comment by Kizzzzurt** [comment]
So they definitely are throttling things. I know I'm late to the party here but it let me do 1 search and get results then not again. I'll try later to see if it'll let me again.

**Comment by sec0ps** [comment]
It worked the first run for a partial scape then I started getting 999 errors. I`m going to guess linkedin see's the generic user-agent string and a quick crawl, then just blacklists the ip+user-agent. Adding in a custom user-agent flag or randomizing the user-agent along with a timing option would likely help.

2017-12-14 19:33:50,182 DEBUG - "GET /title/administration-at-<COMPANYNAMEREMOVED> HTTP/1.1" 999 1461
2017-12-14 19:33:50,188 INFO - Starting new HTTPS connection (1): www.linkedin.com
2017-12-14 19:33:51,413 DEBUG - "GET /title/engineering-at-<COMPANYNAMEREMOVED> HTTP/1.1" 999 1461
2017-12-14 19:33:51,418 INFO - Starting new HTTPS connection (1): www.linkedin.com
2017-12-14 19:33:52,254 DEBUG - "GET /title/it-at-<COMPANYNAMEREMOVED> HTTP/1.1" 999 1461

**Comment by superdale007** [comment]
any resolution to this issue?

**Comment by gojhonny** [comment]
Hey everyone, working on InSpy v3 at the moment. You can expect HTTP 999 errors, these are custom LinkedIn errors that can't be bypassed despite UA randomization. The next version should be released within a couple of days but for now try randomizing the UA and slowing down requests.

**Comment by secureitnetworks** [comment]
Hi I have installed Inspy

But I cannot found --empspy and --techspy after the installation 

root@kali:~# apt install inspy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  inspy
0 upgraded, 1 newly installed, 0 to remove and 589 not upgraded.
Need to get 9,224 B of archives.
After this operation, 46.1 kB of additional disk space will be used.
Get:1 http://kali.download/kali kali-rolling/main amd64 inspy all 3.0.0-0kali2 [9,224 B]
Fetched 9,224 B in 9s (1,063 B/s) 
Selecting previously unselected package inspy.
(Reading database ... 344575 files and directories currently installed.)
Preparing to unpack .../inspy_3.0.0-0kali2_all.deb ...
Unpacking inspy (3.0.0-0kali2) ...
Setting up inspy (3.0.0-0kali2) ...
root@kali:~# inspy -h
usage: inspy [-h] [-v] [--domain DOMAIN] [--email EMAIL] [--titles [file]]
             [--html file] [--csv file] [--json file] [--xml file]
             company

InSpy - A LinkedIn enumeration tool by Jonathan Broche (@LeapSecurity)

positional arguments:
  company          Company name to use for tasks.

optional arguments:
  -h, --help       show this help message and exit
  -v, --version    show program's version number and exit
  --domain DOMAIN  Company domain to use for searching.
  --email EMAIL    Email format to create email addresses with. [Accepted
                   Formats: first.last@xyz.com, last.first@xyz.com,
                   firstl@xyz.com, lfirst@xyz.com, flast@xyz.com,
                   lastf@xyz.com, first@xyz.com, last@xyz.com]
  --titles [file]  Discover employees by title and/or department. Titles and
                   departments are imported from a new line delimited file.
                   [Default: title-list-small.txt]

Output Options:
  --html file      Print results in HTML file.
  --csv file       Print results in CSV format.
  --json file      Print results in JSON.
  --xml file       Print results in XML.
root@kali:~#

**Comment by awanish604** [comment]
Any updates on this issue? not able to work with inspy 3.0
