### ISSUE TITLE
InSpy

### ISSUE THREAD

**Issue by rexftw** [leapsecurity/InSpy#9]
someone help me out with the command line to be used to search for company names with multi words ........example:- appolo tires, mrf tires, etc

**Comment by ernests** [comment]
I think it automatically deals with it. It replaces space with "-"

**Comment by rexftw** [comment]
not really i have tried .  please help out with some info

**Comment by ernests** [comment]
I looked into code - https://github.com/gojhonny/InSpy/blob/master/lib/crawler.py

And it does .replace(' ', '-') for company names.

**Comment by fahadshery** [comment]
@ernests  he is right.
you need to provide `""` when entering company names with space at the `command prompt`
